=== OliverSieweke/oliversieweke/src/utils/reading/book.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Book",
    "type": "object",
    "properties": {
        "identifier": {
            "type": "string",
            "description": "Identifier of the book, corresponding to its file-name."
        },
        "name": {
            "type": "string",
            "description": "Name of the book."
        },
        "subtitle": {
            "type": "string",
            "description": "Subtitle of the book."
        },
        "author": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the author."
                },
                "sameAs": {
                    "type": "string",
                    "format": "uri",
                    "description": "Link to the author's page."
                }
            },
            "required": [
                "name",
                "sameAs"
            ],
            "additionalProperties": false
        },
        "datePublished": {
            "type": "string",
            "pattern": "\\d{4}",
            "description": "Publication date of the book."
        },
        "url": {
            "type": "string",
            "format": "uri",
            "description": "URL to the book (probably an amazon link)."
        },
        "isbn": {
            "type": "string",
            "patter": "^(97(8|9))-\\d{10}$",
            "description": "ISBN-13 of the book."
        },
        "yearRead": {
            "type": "string",
            "pattern": "\\d{4}",
            "description": "Year the book was read."
        },
        "review": {
            "type": "string",
            "maxLength": 300,
            "description": "Review of the book."
        },
        "reviewDateCreated": {
            "type": "integer",
            "description": "Year the book review was written."
        },
        "reviewDatePublished": {
            "type": "string",
            "pattern": "\\d{4}",
            "description": "Year the review was published."
        }
    },
    "required": [
        "identifier",
        "name",
        "author",
        "datePublished",
        "url",
        "isbn",
        "yearRead",
        "review",
        "reviewDateCreated",
        "reviewDatePublished"
    ],
    "additionalProperties": false
}

=== OliverSieweke/oliversieweke/content/reading/object-oriented-js.json
{
    "identifier": "object-oriented-js",
    "name": "The Principles of Object Oriented JavaScript",
    "author": {
        "name": "Nicholas C. Zakas",
        "sameAs": "https://humanwhocodes.com/about/"
    },
    "datePublished": "2014",
    "url": "https://amzn.to/1mmkyCm",
    "isbn": "978-1593275402",
    "yearRead": "2018",
    "reviewDateCreated": 2019,
    "reviewDatePublished": "2019",
    "review": "Book. Verteidigungsministerin als EU-Kommissionschefin vorgeschlagen hat, hat diese mit ihrem Team die politische Werals EU-Kommissionschefin vorgeschlagen hat, vorgeschlagen vorgeschlagen hat, vorgeschlagen hat, vorgeschlagen hat, vorgeschlagen hat, vorgeschlagen hat, hat,  hat dnerie gestartet.ngs  vorgeschlagen hat, hat dnerie gestartet.ngsministerin als EU-Kommifin vorgescaschinerie ges"
}
